queue: default
queues:
  - gestion_cuisine_default

:scheduler:
  :schedule:
    create_calendar_job:
      cron: '0 23 * * 3'   # [min] [hour] [day of month] [month] [day of week 0-6 sun-sat]
      class: "CreateCalendarJob"

    attach_task_and_calendar_job:
      cron: '5 23 * * 3'   # [min] [hour] [day of month] [month] [day of week 0-6 sun-sat]
      class: "AttachTaskAndCalendarJob"

    calcul_vote_job:
      cron: '30 21 * * 1-5'
      class: "CalculVoteJob"

    update_vote_periode_job:
      cron: '30 10 * * 1-5'
      class: "UpdateVotePeriodeJob"

    send_vote_notification_open_job:
      cron: '00 17 * * 1-5'
      class: "SendVoteNotificationOpenJob"

    send_vote_notification_end_job:
      cron: '00 21 * * 1-5'
      class: "SendVoteNotificationEndJob"
